apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    # chart: grafana
    repoURL: https://github.com/RamSreekar/argocd-app-of-apps-example.git # https://grafana.github.io/helm-charts
    targetRevision: HEAD
    path: grafana

    helm:
      valueFiles: 
        - values.yaml
      # valuesObject:
      #   replicas: 2 
        
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true