apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources: # 'sources' instead of source for specifying multiple sources.
    # Chart from chart repo
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.4.1

      helm:
        valueFiles: 
          - $values/values/grafana-values.yaml

    # Values from git
    - repoURL: https://github.com/RamSreekar/argocd-app-of-apps-example.git
      targetRevision: HEAD
      ref: values  
          
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true